name: Prettier
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - run: npm i prettier -g
      - run: npm run format:write

      - name: Show git status (debug)
        run: git status

      - name: Force add all changes
        run: git add -A

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'CI: fix formatting'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          token: ${{ secrets.GITHUB_TOKEN }}
          skip_dirty_check: true  
